Final Project/Final Project/Models/About.cs
namespace Final_Project.Models
{
    public class About : BaseEntity
    {
        public string Title { get; set; }
        public string Desc { get; set; }
        public string Img { get; set; }
    }
}

Final Project/Final Project/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace Final_Project.Models
{
    public class AppUser : IdentityUser
    {
        public string Fullname { get; set; }
    }
}

Final Project/Final Project/Models/Author.cs
namespace Final_Project.Models
{
    public class Author : BaseEntity
    {
        public string FullName { get; set; }
        public string Img { get; set; }

        public ICollection<ProductAuthor> ProductAuthors { get; set; } = new List<ProductAuthor>();
    }
}

Final Project/Final Project/Models/BaseEntity.cs
namespace Final_Project.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now;
    }
}

Final Project/Final Project/Models/Basket.cs
namespace Final_Project.Models
{
    public class Basket : BaseEntity
    {
        public string UserId { get; set; }
        public AppUser User { get; set; }

        public ICollection<BasketItem> BasketItems { get; set; }
    }
}

Final Project/Final Project/Models/BasketItem.cs
namespace Final_Project.Models
{
    public class BasketItem : BaseEntity
    {
        public int BasketId { get; set; }
        public Basket Basket { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

Final Project/Final Project/Models/Blog.cs
namespace Final_Project.Models
{
    public class Blog : BaseEntity
    {
        public string Img { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Final Project/Final Project/Models/EmailSettings.cs
namespace Final_Project.Models
{
    public class EmailSettings
    {
        public string SmtpServer { get; set; }
        public int Port { get; set; }
        public string SenderEmail { get; set; }
        public string SenderPassword { get; set; }
    }
}

Final Project/Final Project/Models/FeaturedBook.cs
namespace Final_Project.Models
{
    public class FeaturedBook : BaseEntity
    {
        public string Img { get; set; }    
        public string Title { get; set; }   
        public string Author { get; set; }  
        public decimal Price { get; set; }
    }
}

Final Project/Final Project/Models/Genre.cs
namespace Final_Project.Models
{
    public class Genre : BaseEntity
    {
        public string Name { get; set; }

        public ICollection<ProductGenre> ProductGenres { get; set; }
    }
}

Final Project/Final Project/Models/Partner.cs
namespace Final_Project.Models
{
    public class Partner : BaseEntity
    {
        public string Img { get; set; }

    }
}

Final Project/Final Project/Models/Product.cs
namespace Final_Project.Models
{
    public class Product : BaseEntity
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Img { get; set; }
        public ICollection<ProductAuthor> ProductAuthors { get; set; } = new List<ProductAuthor>();
        public ICollection<ProductGenre> ProductGenres { get; set; }
    }
}

Final Project/Final Project/Models/ProductAuthor.cs
namespace Final_Project.Models
{
    public class ProductAuthor
    {
        public int ProductId { get; set; }
        public Product Product { get; set; }

        public int AuthorId { get; set; }
        public Author Author { get; set; }
    }
}

Final Project/Final Project/Models/ProductGenre.cs
namespace Final_Project.Models
{
    public class ProductGenre
    {
        public int ProductId { get; set; }
        public Product Product { get; set; }

        public int GenreId { get; set; }
        public Genre Genre { get; set; }
    }
}

Final Project/Final Project/Models/Quote.cs
namespace Final_Project.Models
{
    public class Quote : BaseEntity
    {
        public string Content { get; set; }
        public string Author { get; set; }
    }
}

Final Project/Final Project/Models/Setting.cs
namespace Final_Project.Models
{
    public class Setting : BaseEntity
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }
}

Final Project/Final Project/Models/Slider.cs
namespace Final_Project.Models
{
    public class Slider : BaseEntity
    {
        public string Img { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Final Project/Final Project/Models/Subscriber.cs
namespace Final_Project.Models
{
    public class Subscriber : BaseEntity
    {
        public string Email { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmationToken { get; set; }
    }
}

Final Project/Final Project/Models/Team.cs
namespace Final_Project.Models
{
    public class Team : BaseEntity
    {
        public string Name { get; set; }
        public string Position { get; set; }
        public string Img { get; set; }
    }
}

Final Project/Final Project/Models/Wishlist.cs
namespace Final_Project.Models
{
    public class Wishlist : BaseEntity
    {
        public string AppUserId { get; set; }
        public AppUser AppUser { get; set; }

        public ICollection<WishlistItem> WishlistItems { get; set; } = new List<WishlistItem>();
    }
}

Final Project/Final Project/Models/WishlistItem.cs
namespace Final_Project.Models
{
    public class WishlistItem : BaseEntity
    {
        public int WishlistId { get; set; }
        public Wishlist Wishlist { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

Final Project/Final Project/ViewModels/User/Wishlist/WishlistVM.cs
namespace Final_Project.ViewModels.User.Wishlist
{
    public class WishlistVM
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public decimal Price { get; set; }
    }
}

Final Project/Final Project/Controllers/WishlistController.cs
using Final_Project.Models;
using Final_Project.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

[Authorize]
public class WishlistController : Controller
{
    private readonly IWishlistService _wishlistService;
    private readonly UserManager<AppUser> _userManager;

    public WishlistController(IWishlistService wishlistService, UserManager<AppUser> userManager)
    {
        _wishlistService = wishlistService;
        _userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        var user = await _userManager.GetUserAsync(User);
        var wishlist = await _wishlistService.GetAllAsync(user.Id);
        return View(wishlist);
    }

    public async Task<IActionResult> Add(int productId)
    {
        var userId = _userManager.GetUserId(User);
        await _wishlistService.AddAsync(userId, productId);
        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> Remove(int productId)
    {
        var user = await _userManager.GetUserAsync(User);
        await _wishlistService.RemoveAsync(user.Id, productId);
        return RedirectToAction("Index");
    }
}

Final Project/Final Project/ViewComponents/Wishlist/WishlistViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Final_Project.Models;
using Final_Project.Services.Interfaces;
using Final_Project.ViewModels.User.Wishlist;

public class WishlistViewComponent : ViewComponent
{
    private readonly IWishlistService _wishlistService;
    private readonly UserManager<AppUser> _userManager;

    public WishlistViewComponent(IWishlistService wishlistService, UserManager<AppUser> userManager)
    {
        _wishlistService = wishlistService;
        _userManager = userManager;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        if (!User.Identity.IsAuthenticated)
        {
            // İstifadəçi login deyilsə boş siyahı qaytar
            return View(new List<WishlistVM>());
        }

        var user = await _userManager.GetUserAsync(HttpContext.User);
        var wishlist = await _wishlistService.GetAllAsync(user.Id);

        return View(wishlist);
    }
}

Final Project/Final Project/Views/Shared/Components/Wishlist/Default.cshtml
@model List<WishlistVM>

<main>
    <section class="hero-2">
        <h2>Wishlist</h2>
    </section>
    <section class="py-5 cart-desktop container">
        <table class="cart-desktop-table">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Add To Cart</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                @if (!Model.Any())
                {
                    <tr><td colspan="5" class="text-center">Wishlist is empty</td></tr>
                }
                else
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="cart-item-img">
                                <img src="~/uploads/products/@item.ProductImage" class="img-fluid" alt="@item.ProductName" />
                            </td>
                            <td>@item.ProductName</td>
                            <td>@item.Price.ToString("C")</td>
                            <td>
                                <form asp-controller="Basket" asp-action="Add" method="post">
                                    <input type="hidden" name="productId" value="@item.ProductId" />
                                    <button type="submit" class="by-nw">Add To Cart</button>
                                </form>
                            </td>
                            <td>
                                <form asp-controller="Wishlist" asp-action="Remove" method="post">
                                    <input type="hidden" name="productId" value="@item.ProductId" />
                                    <button type="submit" class="btn btn-link p-0">
                                        <i class="fa-solid fa-trash-xmark"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </section>

    <section class="py-5 cart-mobile d-none container">
        @if (!Model.Any())
        {
            <div class="text-center">Wishlist is empty</div>
        }
        else
        {
            @foreach (var item in Model)
            {
                <div class="row g-2 cart-item-mobile">
                    <div class="col-3">
                        <img src="~/uploads/products/@item.ProductImage" class="img-fluid" alt="@item.ProductName" />
                    </div>
                    <div class="col-4">
                        <h2 class="book-name-mobile">@item.ProductName</h2>
                        <h4 class="book-price-mobile">@item.Price.ToString("C")</h4>
                    </div>
                    <div class="col-5 cart-mobile-right text-end">
                        <form asp-controller="Wishlist" asp-action="Remove" method="post" class="d-inline">
                            <input type="hidden" name="productId" value="@item.ProductId" />
                            <button type="submit" class="mobile-delete-btn">
                                <i class="fa-solid fa-trash-xmark"></i>
                            </button>
                        </form>
                        <form asp-controller="Basket" asp-action="Add" method="post" class="d-inline ms-2" style="display:inline;">
                            <input type="hidden" name="productId" value="@item.ProductId" />
                            <button type="submit" style="border:none; background:none; padding:0; cursor:pointer;" title="Add to Cart">
                                <i class="fa-regular fa-cart-plus" style="font-size:1.3rem; color:#000;"></i>
                            </button>
                        </form>

                    </div>
                </div>
            }
        }
    </section>
</main>